version: '3.8'
services:
  # NestJS アプリケーションの定義を追加
  app:
    build: ../.
    env_file:
      - ../.env.test
    links:
      - mongodb
  mongodb:
    image: mongo:7.0 #arm64v8/mongo:7.0から変更（AMD,ARM両方倒錯するように）
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: azure-dev
      MONGO_INITDB_ROOT_PASSWORD: azure-dev
      MONGO_INITDB_DATABASE: azure-dev
      TZ: Asia/Tokyo
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb