version: '3.8'
services:
  mongodb:
    image: arm64v8/mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: azure-dev
      MONGO_INITDB_ROOT_PASSWORD: azure-dev
      MONGO_INITDB_DATABASE: azure-dev
      TZ: Asia/Tokyo
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb