# main ブランチに何らかの commit が追加されたら走らせる
on:
  workflow_dispatch:  # 수동 트리거
  push:
    branches:
      - devGithubAction

env:
  AZURE_FUNCTION_APP_NAME: azure-nestjs-sample
  AZURE_FUNCTION_APP_PACKAGE_PATH: '.'
  NODE_VERSION: '18.15.0'
  AZURE_CLIENT_ID: 'e773dbaf-8fad-4e0e-a09f-0cf6acc650ab'
  AZURE_TENANT_ID: 'af786cca-2bb4-46f0-bb34-0685f845f7e9'
  AZURE_SUBSCRIPTION_ID: '3e556a91-b9e7-4c60-bedd-3136b8c07447'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # id-token 권한 부여
      contents: read   # 리포지토리 콘텐츠 읽기 권한
    steps:
      - name: 'Checkout GitHub Action'
#        uses: actions/checkout@master
        uses: actions/checkout@v3      # 최신 버전 v3 사용

      # If you want to use Azure RBAC instead of Publish Profile, then uncomment the task below
      # - name: 'Login via Azure CLI'
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }} # set up AZURE_RBAC_CREDENTIALS secrets in your repository

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@3 # 최신 버전 v4 사용
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Install Dependencies and build.'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTION_APP_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          npm run test --if-present
          popd

      # Azure 로그인 액션 추가
#      - name: 'Azure Login'
#        uses: azure/login@v2
#        with:
#          client-id: ${{ env.AZURE_CLIENT_ID }}
#          tenant-id: ${{ env.AZURE_TENANT_ID }}
#          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTION_APP_NAME }}
          package: ${{ env.AZURE_FUNCTION_APP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          # Remove publish-profile to use Azure RBAC
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples