# main ブランチに何らかの commit が追加されたら走らせる
on:
  workflow_dispatch:  # 수동 트리거
  push:
    branches:
      - devGithubAction

env:
  AZURE_FUNCTION_APP_NAME: azure-nestjs-sample
  AZURE_FUNCTION_APP_PACKAGE_PATH: '.'
  NODE_VERSION: '18.15.0'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
#        uses: actions/checkout@master
        uses: actions/checkout@v3  # 최신 버전 v3 사용

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3 # 최신 버전 v3 사용
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: 'Install Dependencies and build.'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTION_APP_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          popd

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTION_APP_NAME }}
          package: ${{ env.AZURE_FUNCTION_APP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTION_APP_PUBLISH_PROFILE }}

# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples